version: '3'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.builder
      args:
        BRANCH: ${BUILDKITE_BRANCH}
        COMMIT: ${BUILDKITE_COMMIT}
    command: "/build/docker-entrypoint.sh"
    volumes:
      - ../:/build

  cloud-sdk:
    image: google/cloud-sdk:latest
    environment:
        - GCLOUD_CREDENTIAL_FILE=/tmp/gcloud-credential-file
        - BUCKET
        - PROJECT
        - BUILDKITE_AGENT_ACCESS_TOKEN
        - BUILDKITE_PIPELINE_SLUG
        - BUILDKITE_BRANCH
        - BUILDKITE_BUILD_ID
    working_dir: "/app"
    command: "/app/.buildkite/create-image.sh"
    volumes:
      - /tmp/docker-credential-file:/tmp/gcloud-credential-file
      - ../:/app/
      - /usr/sbin/buildkite-agent:/usr/bin/buildkite-agent