steps:
  - label: ":building_construction: Building Image"
    concurrency: 1
    concurrency_group: "gce-buildkite-alpine/1"
    artifact_paths: ./*.tar.gz
    plugins:
      docker-compose#v2.5.1:
        config: .buildkite/docker-compose.yml
        run: builder
    retry:
      automatic:
        - exit_status: "*"
          limit: 10


  - wait

  - label: ":arrow_up: creating image"
    command: /app/.buildkite/create-image.sh
    concurrency: 1
    concurrency_group: "gce-buildkite-alpine/1"
    plugins:
      docker-compose#v2.5.1:
        config: .buildkite/docker-compose.yml
        run: cloud-sdk