steps:
  - label: ":building_construction: Building Image"
    artifact_paths: ./*.tar.gz
    plugins:
      docker-compose#v2.5.1:
        config: .buildkite/docker-compose.yml
        run: builder
    retry:
      automatic:
        - exit_status: "*"
          limit: 10


  - wait

  - label: ":arrow_up: creating image"
    command: "/app/.buildkite/create-image.sh"
    plugins:
      docker-compose#v2.5.1:
        config: .buildkite/docker-compose.yml
        run: cloud-sdk


  - wait

  - block: "Deploy :rocket:"
    prompt: "Release image and restart buildkite agents?"
  - command: "/app/.buildkite/release-image.sh"
    plugins:
      docker-compose#v2.5.1:
        config: .buildkite/docker-compose.yml
        run: cloud-sdk